rvm:
- 1.9.3
branches:
  only:
    - develop
python:
- 2.7
before_script:
- sudo apt-get update
- sudo apt-get install postgis
- sudo apt-get install python-gdal
- sudo pip install -r requirements/base.txt
- sudo pip install -r requirements/test.txt
script:
- python hsmapper/manage.py test core
